# ---- Stage 1: Build ----
FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o user-service ./cmd/server/main.go

# ---- Stage 2: Run ----
FROM gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=builder /app/user-service .
COPY config.json .

CMD ["./user-service"]